package com.example.projectuas;

import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;
import com.google.android.material.bottomnavigation.BottomNavigationView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.navigation.NavController;
import androidx.navigation.Navigation;
import androidx.navigation.ui.AppBarConfiguration;
import androidx.navigation.ui.NavigationUI;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;

import model.Companies;
import model.ListedCompany;
import model.User;
import model.UserArray;

public class MainActivity extends AppCompatActivity {

    private Intent intent;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        BottomNavigationView navView = findViewById(R.id.nav_view);
        // Passing each menu ID as a set of Ids because each
        // menu should be considered as top level destinations.
        AppBarConfiguration appBarConfiguration = new AppBarConfiguration.Builder(
                R.id.navigation_home, R.id.navigation_portfolio, R.id.navigation_news, R.id.navigation_profile)
                .build();
        NavController navController = Navigation.findNavController(this, R.id.nav_host_fragment);
        NavigationUI.setupWithNavController(navView, navController);

        intent = getIntent();

        Companies.getListedCompanies().clear();
        Companies.getListedCompanies().add(new ListedCompany("MMM"));
        Companies.getListedCompanies().add(new ListedCompany("ABT"));
        Companies.getListedCompanies().add(new ListedCompany("ABBV"));
        Companies.getListedCompanies().add(new ListedCompany("ABMD"));
        Companies.getListedCompanies().add(new ListedCompany("ACN"));
        Companies.getListedCompanies().add(new ListedCompany("ATVI"));
        Companies.getListedCompanies().add(new ListedCompany("ADBE"));
        Companies.getListedCompanies().add(new ListedCompany("AMD"));
        Companies.getListedCompanies().add(new ListedCompany("AAP"));
        Companies.getListedCompanies().add(new ListedCompany("AES"));
        Companies.getListedCompanies().add(new ListedCompany("AFL"));
        Companies.getListedCompanies().add(new ListedCompany("A"));
        Companies.getListedCompanies().add(new ListedCompany("APD"));
        Companies.getListedCompanies().add(new ListedCompany("AKAM"));
        Companies.getListedCompanies().add(new ListedCompany("ALK"));
        Companies.getListedCompanies().add(new ListedCompany("ALB"));
        Companies.getListedCompanies().add(new ListedCompany("ARE"));
        Companies.getListedCompanies().add(new ListedCompany("ALXN"));
        Companies.getListedCompanies().add(new ListedCompany("ALGN"));
        Companies.getListedCompanies().add(new ListedCompany("ALLE"));
        Companies.getListedCompanies().add(new ListedCompany("LNT"));
        Companies.getListedCompanies().add(new ListedCompany("ALL"));
        Companies.getListedCompanies().add(new ListedCompany("GOOGL"));
        Companies.getListedCompanies().add(new ListedCompany("GOOG"));
        Companies.getListedCompanies().add(new ListedCompany("MO"));
        Companies.getListedCompanies().add(new ListedCompany("AMZN"));
        Companies.getListedCompanies().add(new ListedCompany("AMCR"));
        Companies.getListedCompanies().add(new ListedCompany("AEE"));
        Companies.getListedCompanies().add(new ListedCompany("AAL"));
        Companies.getListedCompanies().add(new ListedCompany("AEP"));
        Companies.getListedCompanies().add(new ListedCompany("AXP"));
        Companies.getListedCompanies().add(new ListedCompany("AIG"));
        Companies.getListedCompanies().add(new ListedCompany("AMT"));
        Companies.getListedCompanies().add(new ListedCompany("AWK"));
        Companies.getListedCompanies().add(new ListedCompany("AMP"));
        Companies.getListedCompanies().add(new ListedCompany("ABC"));
        Companies.getListedCompanies().add(new ListedCompany("AME"));
        Companies.getListedCompanies().add(new ListedCompany("AMGN"));
        Companies.getListedCompanies().add(new ListedCompany("APH"));
        Companies.getListedCompanies().add(new ListedCompany("ADI"));
        Companies.getListedCompanies().add(new ListedCompany("ANSS"));
        Companies.getListedCompanies().add(new ListedCompany("ANTM"));
        Companies.getListedCompanies().add(new ListedCompany("AON"));
        Companies.getListedCompanies().add(new ListedCompany("AOS"));
        Companies.getListedCompanies().add(new ListedCompany("APA"));
        Companies.getListedCompanies().add(new ListedCompany("AAPL"));
        Companies.getListedCompanies().add(new ListedCompany("AMAT"));
        Companies.getListedCompanies().add(new ListedCompany("APTV"));
        Companies.getListedCompanies().add(new ListedCompany("ADM"));
        Companies.getListedCompanies().add(new ListedCompany("ANET"));
        Companies.getListedCompanies().add(new ListedCompany("AJG"));
        Companies.getListedCompanies().add(new ListedCompany("AIZ"));
        Companies.getListedCompanies().add(new ListedCompany("T"));
        Companies.getListedCompanies().add(new ListedCompany("ATO"));
        Companies.getListedCompanies().add(new ListedCompany("ADSK"));
        Companies.getListedCompanies().add(new ListedCompany("ADP"));
        Companies.getListedCompanies().add(new ListedCompany("AZO"));
        Companies.getListedCompanies().add(new ListedCompany("AVB"));
        Companies.getListedCompanies().add(new ListedCompany("AVY"));
        Companies.getListedCompanies().add(new ListedCompany("BKR"));
        Companies.getListedCompanies().add(new ListedCompany("BLL"));
        Companies.getListedCompanies().add(new ListedCompany("BAC"));
        Companies.getListedCompanies().add(new ListedCompany("BK"));
        Companies.getListedCompanies().add(new ListedCompany("BAX"));
        Companies.getListedCompanies().add(new ListedCompany("BDX"));
        Companies.getListedCompanies().add(new ListedCompany("BRK.B"));
        Companies.getListedCompanies().add(new ListedCompany("BBY"));
        Companies.getListedCompanies().add(new ListedCompany("BIO"));
        Companies.getListedCompanies().add(new ListedCompany("BIIB"));
        Companies.getListedCompanies().add(new ListedCompany("BLK"));
        Companies.getListedCompanies().add(new ListedCompany("BA"));
        Companies.getListedCompanies().add(new ListedCompany("BKNG"));
        Companies.getListedCompanies().add(new ListedCompany("BWA"));
        Companies.getListedCompanies().add(new ListedCompany("BXP"));
        Companies.getListedCompanies().add(new ListedCompany("BSX"));
        Companies.getListedCompanies().add(new ListedCompany("BMY"));
        Companies.getListedCompanies().add(new ListedCompany("AVGO"));
        Companies.getListedCompanies().add(new ListedCompany("BR"));
        Companies.getListedCompanies().add(new ListedCompany("BF.B"));
        Companies.getListedCompanies().add(new ListedCompany("CHRW"));
        Companies.getListedCompanies().add(new ListedCompany("COG"));
        Companies.getListedCompanies().add(new ListedCompany("CDNS"));
        Companies.getListedCompanies().add(new ListedCompany("CZR"));
        Companies.getListedCompanies().add(new ListedCompany("CPB"));
        Companies.getListedCompanies().add(new ListedCompany("COF"));
        Companies.getListedCompanies().add(new ListedCompany("CAH"));
        Companies.getListedCompanies().add(new ListedCompany("KMX"));
        Companies.getListedCompanies().add(new ListedCompany("CCL"));
        Companies.getListedCompanies().add(new ListedCompany("CARR"));
        Companies.getListedCompanies().add(new ListedCompany("CTLT"));
        Companies.getListedCompanies().add(new ListedCompany("CAT"));
        Companies.getListedCompanies().add(new ListedCompany("CBOE"));
        Companies.getListedCompanies().add(new ListedCompany("CBRE"));
        Companies.getListedCompanies().add(new ListedCompany("CDW"));
        Companies.getListedCompanies().add(new ListedCompany("CE"));
        Companies.getListedCompanies().add(new ListedCompany("CNC"));
        Companies.getListedCompanies().add(new ListedCompany("CNP"));
        Companies.getListedCompanies().add(new ListedCompany("CERN"));
        Companies.getListedCompanies().add(new ListedCompany("CF"));
        Companies.getListedCompanies().add(new ListedCompany("CRL"));
        Companies.getListedCompanies().add(new ListedCompany("SCHW"));
        Companies.getListedCompanies().add(new ListedCompany("CHTR"));
        Companies.getListedCompanies().add(new ListedCompany("CVX"));
        Companies.getListedCompanies().add(new ListedCompany("CMG"));
        Companies.getListedCompanies().add(new ListedCompany("CB"));
        Companies.getListedCompanies().add(new ListedCompany("CHD"));
        Companies.getListedCompanies().add(new ListedCompany("CI"));
        Companies.getListedCompanies().add(new ListedCompany("CINF"));
        Companies.getListedCompanies().add(new ListedCompany("CTAS"));
        Companies.getListedCompanies().add(new ListedCompany("CSCO"));
        Companies.getListedCompanies().add(new ListedCompany("C"));
        Companies.getListedCompanies().add(new ListedCompany("CFG"));
        Companies.getListedCompanies().add(new ListedCompany("CTXS"));
        Companies.getListedCompanies().add(new ListedCompany("CLX"));
        Companies.getListedCompanies().add(new ListedCompany("CME"));
        Companies.getListedCompanies().add(new ListedCompany("CMS"));
        Companies.getListedCompanies().add(new ListedCompany("KO"));
        Companies.getListedCompanies().add(new ListedCompany("CTSH"));
        Companies.getListedCompanies().add(new ListedCompany("CL"));
        Companies.getListedCompanies().add(new ListedCompany("CMCSA"));
        Companies.getListedCompanies().add(new ListedCompany("CMA"));
        Companies.getListedCompanies().add(new ListedCompany("CAG"));
        Companies.getListedCompanies().add(new ListedCompany("COP"));
        Companies.getListedCompanies().add(new ListedCompany("ED"));
        Companies.getListedCompanies().add(new ListedCompany("STZ"));
        Companies.getListedCompanies().add(new ListedCompany("COO"));
        Companies.getListedCompanies().add(new ListedCompany("CPRT"));
        Companies.getListedCompanies().add(new ListedCompany("GLW"));
        Companies.getListedCompanies().add(new ListedCompany("CTVA"));
        Companies.getListedCompanies().add(new ListedCompany("COST"));
        Companies.getListedCompanies().add(new ListedCompany("CCI"));
        Companies.getListedCompanies().add(new ListedCompany("CSX"));
        Companies.getListedCompanies().add(new ListedCompany("CMI"));
        Companies.getListedCompanies().add(new ListedCompany("CVS"));
        Companies.getListedCompanies().add(new ListedCompany("DHI"));
        Companies.getListedCompanies().add(new ListedCompany("DHR"));
        Companies.getListedCompanies().add(new ListedCompany("DRI"));
        Companies.getListedCompanies().add(new ListedCompany("DVA"));
        Companies.getListedCompanies().add(new ListedCompany("DE"));
        Companies.getListedCompanies().add(new ListedCompany("DAL"));
        Companies.getListedCompanies().add(new ListedCompany("XRAY"));
        Companies.getListedCompanies().add(new ListedCompany("DVN"));
        Companies.getListedCompanies().add(new ListedCompany("DXCM"));
        Companies.getListedCompanies().add(new ListedCompany("FANG"));
        Companies.getListedCompanies().add(new ListedCompany("DLR"));
        Companies.getListedCompanies().add(new ListedCompany("DFS"));
        Companies.getListedCompanies().add(new ListedCompany("DISCA"));
        Companies.getListedCompanies().add(new ListedCompany("DISCK"));
        Companies.getListedCompanies().add(new ListedCompany("DISH"));
        Companies.getListedCompanies().add(new ListedCompany("DG"));
        Companies.getListedCompanies().add(new ListedCompany("DLTR"));
        Companies.getListedCompanies().add(new ListedCompany("D"));
        Companies.getListedCompanies().add(new ListedCompany("DPZ"));
        Companies.getListedCompanies().add(new ListedCompany("DOV"));
        Companies.getListedCompanies().add(new ListedCompany("DOW"));
        Companies.getListedCompanies().add(new ListedCompany("DTE"));
        Companies.getListedCompanies().add(new ListedCompany("DUK"));
        Companies.getListedCompanies().add(new ListedCompany("DRE"));
        Companies.getListedCompanies().add(new ListedCompany("DD"));
        Companies.getListedCompanies().add(new ListedCompany("DXC"));
        Companies.getListedCompanies().add(new ListedCompany("EMN"));
        Companies.getListedCompanies().add(new ListedCompany("ETN"));
        Companies.getListedCompanies().add(new ListedCompany("EBAY"));
        Companies.getListedCompanies().add(new ListedCompany("ECL"));
        Companies.getListedCompanies().add(new ListedCompany("EIX"));
        Companies.getListedCompanies().add(new ListedCompany("EW"));
        Companies.getListedCompanies().add(new ListedCompany("EA"));
        Companies.getListedCompanies().add(new ListedCompany("EMR"));
        Companies.getListedCompanies().add(new ListedCompany("ENPH"));
        Companies.getListedCompanies().add(new ListedCompany("ETR"));
        Companies.getListedCompanies().add(new ListedCompany("EOG"));
        Companies.getListedCompanies().add(new ListedCompany("EFX"));
        Companies.getListedCompanies().add(new ListedCompany("EQIX"));
        Companies.getListedCompanies().add(new ListedCompany("EQR"));
        Companies.getListedCompanies().add(new ListedCompany("ESS"));
        Companies.getListedCompanies().add(new ListedCompany("EL"));
        Companies.getListedCompanies().add(new ListedCompany("ETSY"));
        Companies.getListedCompanies().add(new ListedCompany("EVRG"));
        Companies.getListedCompanies().add(new ListedCompany("ES"));
        Companies.getListedCompanies().add(new ListedCompany("RE"));
        Companies.getListedCompanies().add(new ListedCompany("EXC"));
        Companies.getListedCompanies().add(new ListedCompany("EXPE"));
        Companies.getListedCompanies().add(new ListedCompany("EXPD"));
        Companies.getListedCompanies().add(new ListedCompany("EXR"));
        Companies.getListedCompanies().add(new ListedCompany("XOM"));
        Companies.getListedCompanies().add(new ListedCompany("FFIV"));
        Companies.getListedCompanies().add(new ListedCompany("FB"));
        Companies.getListedCompanies().add(new ListedCompany("FAST"));
        Companies.getListedCompanies().add(new ListedCompany("FRT"));
        Companies.getListedCompanies().add(new ListedCompany("FDX"));
        Companies.getListedCompanies().add(new ListedCompany("FIS"));
        Companies.getListedCompanies().add(new ListedCompany("FITB"));
        Companies.getListedCompanies().add(new ListedCompany("FE"));
        Companies.getListedCompanies().add(new ListedCompany("FRC"));
        Companies.getListedCompanies().add(new ListedCompany("FISV"));
        Companies.getListedCompanies().add(new ListedCompany("FLT"));
        Companies.getListedCompanies().add(new ListedCompany("FMC"));
        Companies.getListedCompanies().add(new ListedCompany("F"));
        Companies.getListedCompanies().add(new ListedCompany("FTNT"));
        Companies.getListedCompanies().add(new ListedCompany("FTV"));
        Companies.getListedCompanies().add(new ListedCompany("FBHS"));
        Companies.getListedCompanies().add(new ListedCompany("FOXA"));
        Companies.getListedCompanies().add(new ListedCompany("FOX"));
        Companies.getListedCompanies().add(new ListedCompany("BEN"));
        Companies.getListedCompanies().add(new ListedCompany("FCX"));
        Companies.getListedCompanies().add(new ListedCompany("GPS"));
        Companies.getListedCompanies().add(new ListedCompany("GRMN"));
        Companies.getListedCompanies().add(new ListedCompany("IT"));
        Companies.getListedCompanies().add(new ListedCompany("GNRC"));
        Companies.getListedCompanies().add(new ListedCompany("GD"));
        Companies.getListedCompanies().add(new ListedCompany("GE"));
        Companies.getListedCompanies().add(new ListedCompany("GIS"));
        Companies.getListedCompanies().add(new ListedCompany("GM"));
        Companies.getListedCompanies().add(new ListedCompany("GPC"));
        Companies.getListedCompanies().add(new ListedCompany("GILD"));
        Companies.getListedCompanies().add(new ListedCompany("GL"));
        Companies.getListedCompanies().add(new ListedCompany("GPN"));
        Companies.getListedCompanies().add(new ListedCompany("GS"));
        Companies.getListedCompanies().add(new ListedCompany("GWW"));
        Companies.getListedCompanies().add(new ListedCompany("HAL"));
        Companies.getListedCompanies().add(new ListedCompany("HBI"));
        Companies.getListedCompanies().add(new ListedCompany("HIG"));
        Companies.getListedCompanies().add(new ListedCompany("HAS"));
        Companies.getListedCompanies().add(new ListedCompany("HCA"));
        Companies.getListedCompanies().add(new ListedCompany("PEAK"));
        Companies.getListedCompanies().add(new ListedCompany("HSIC"));
        Companies.getListedCompanies().add(new ListedCompany("HSY"));
        Companies.getListedCompanies().add(new ListedCompany("HES"));
        Companies.getListedCompanies().add(new ListedCompany("HPE"));
        Companies.getListedCompanies().add(new ListedCompany("HLT"));
        Companies.getListedCompanies().add(new ListedCompany("HOLX"));
        Companies.getListedCompanies().add(new ListedCompany("HD"));
        Companies.getListedCompanies().add(new ListedCompany("HON"));
        Companies.getListedCompanies().add(new ListedCompany("HRL"));
        Companies.getListedCompanies().add(new ListedCompany("HST"));
        Companies.getListedCompanies().add(new ListedCompany("HWM"));
        Companies.getListedCompanies().add(new ListedCompany("HPQ"));
        Companies.getListedCompanies().add(new ListedCompany("HUM"));
        Companies.getListedCompanies().add(new ListedCompany("HBAN"));
        Companies.getListedCompanies().add(new ListedCompany("HII"));
        Companies.getListedCompanies().add(new ListedCompany("IEX"));
        Companies.getListedCompanies().add(new ListedCompany("IDXX"));
        Companies.getListedCompanies().add(new ListedCompany("INFO"));
        Companies.getListedCompanies().add(new ListedCompany("ITW"));
        Companies.getListedCompanies().add(new ListedCompany("ILMN"));
        Companies.getListedCompanies().add(new ListedCompany("INCY"));
        Companies.getListedCompanies().add(new ListedCompany("IR"));
        Companies.getListedCompanies().add(new ListedCompany("INTC"));
        Companies.getListedCompanies().add(new ListedCompany("ICE"));
        Companies.getListedCompanies().add(new ListedCompany("IBM"));
        Companies.getListedCompanies().add(new ListedCompany("IP"));
        Companies.getListedCompanies().add(new ListedCompany("IPG"));
        Companies.getListedCompanies().add(new ListedCompany("IFF"));
        Companies.getListedCompanies().add(new ListedCompany("INTU"));
        Companies.getListedCompanies().add(new ListedCompany("ISRG"));
        Companies.getListedCompanies().add(new ListedCompany("IVZ"));
        Companies.getListedCompanies().add(new ListedCompany("IPGP"));
        Companies.getListedCompanies().add(new ListedCompany("IQV"));
        Companies.getListedCompanies().add(new ListedCompany("IRM"));
        Companies.getListedCompanies().add(new ListedCompany("JKHY"));
        Companies.getListedCompanies().add(new ListedCompany("J"));
        Companies.getListedCompanies().add(new ListedCompany("JBHT"));
        Companies.getListedCompanies().add(new ListedCompany("SJM"));
        Companies.getListedCompanies().add(new ListedCompany("JNJ"));
        Companies.getListedCompanies().add(new ListedCompany("JCI"));
        Companies.getListedCompanies().add(new ListedCompany("JPM"));
        Companies.getListedCompanies().add(new ListedCompany("JNPR"));
        Companies.getListedCompanies().add(new ListedCompany("KSU"));
        Companies.getListedCompanies().add(new ListedCompany("K"));
        Companies.getListedCompanies().add(new ListedCompany("KEY"));
        Companies.getListedCompanies().add(new ListedCompany("KEYS"));
        Companies.getListedCompanies().add(new ListedCompany("KMB"));
        Companies.getListedCompanies().add(new ListedCompany("KIM"));
        Companies.getListedCompanies().add(new ListedCompany("KMI"));
        Companies.getListedCompanies().add(new ListedCompany("KLAC"));
        Companies.getListedCompanies().add(new ListedCompany("KHC"));
        Companies.getListedCompanies().add(new ListedCompany("KR"));
        Companies.getListedCompanies().add(new ListedCompany("LB"));
        Companies.getListedCompanies().add(new ListedCompany("LHX"));
        Companies.getListedCompanies().add(new ListedCompany("LH"));
        Companies.getListedCompanies().add(new ListedCompany("LRCX"));
        Companies.getListedCompanies().add(new ListedCompany("LW"));
        Companies.getListedCompanies().add(new ListedCompany("LVS"));
        Companies.getListedCompanies().add(new ListedCompany("LEG"));
        Companies.getListedCompanies().add(new ListedCompany("LDOS"));
        Companies.getListedCompanies().add(new ListedCompany("LEN"));
        Companies.getListedCompanies().add(new ListedCompany("LLY"));
        Companies.getListedCompanies().add(new ListedCompany("LNC"));
        Companies.getListedCompanies().add(new ListedCompany("LIN"));
        Companies.getListedCompanies().add(new ListedCompany("LYV"));
        Companies.getListedCompanies().add(new ListedCompany("LKQ"));
        Companies.getListedCompanies().add(new ListedCompany("LMT"));
        Companies.getListedCompanies().add(new ListedCompany("L"));
        Companies.getListedCompanies().add(new ListedCompany("LOW"));
        Companies.getListedCompanies().add(new ListedCompany("LUMN"));
        Companies.getListedCompanies().add(new ListedCompany("LYB"));
        Companies.getListedCompanies().add(new ListedCompany("MTB"));
        Companies.getListedCompanies().add(new ListedCompany("MRO"));
        Companies.getListedCompanies().add(new ListedCompany("MPC"));
        Companies.getListedCompanies().add(new ListedCompany("MKTX"));
        Companies.getListedCompanies().add(new ListedCompany("MAR"));
        Companies.getListedCompanies().add(new ListedCompany("MMC"));
        Companies.getListedCompanies().add(new ListedCompany("MLM"));
        Companies.getListedCompanies().add(new ListedCompany("MAS"));
        Companies.getListedCompanies().add(new ListedCompany("MA"));
        Companies.getListedCompanies().add(new ListedCompany("MKC"));
        Companies.getListedCompanies().add(new ListedCompany("MXIM"));
        Companies.getListedCompanies().add(new ListedCompany("MCD"));
        Companies.getListedCompanies().add(new ListedCompany("MCK"));
        Companies.getListedCompanies().add(new ListedCompany("MDT"));
        Companies.getListedCompanies().add(new ListedCompany("MRK"));
        Companies.getListedCompanies().add(new ListedCompany("MET"));
        Companies.getListedCompanies().add(new ListedCompany("MTD"));
        Companies.getListedCompanies().add(new ListedCompany("MGM"));
        Companies.getListedCompanies().add(new ListedCompany("MCHP"));
        Companies.getListedCompanies().add(new ListedCompany("MU"));
        Companies.getListedCompanies().add(new ListedCompany("MSFT"));
        Companies.getListedCompanies().add(new ListedCompany("MAA"));
        Companies.getListedCompanies().add(new ListedCompany("MHK"));
        Companies.getListedCompanies().add(new ListedCompany("TAP"));
        Companies.getListedCompanies().add(new ListedCompany("MDLZ"));
        Companies.getListedCompanies().add(new ListedCompany("MPWR"));
        Companies.getListedCompanies().add(new ListedCompany("MNST"));
        Companies.getListedCompanies().add(new ListedCompany("MCO"));
        Companies.getListedCompanies().add(new ListedCompany("MS"));
        Companies.getListedCompanies().add(new ListedCompany("MOS"));
        Companies.getListedCompanies().add(new ListedCompany("MSI"));
        Companies.getListedCompanies().add(new ListedCompany("MSCI"));
        Companies.getListedCompanies().add(new ListedCompany("NDAQ"));
        Companies.getListedCompanies().add(new ListedCompany("NTAP"));
        Companies.getListedCompanies().add(new ListedCompany("NFLX"));
        Companies.getListedCompanies().add(new ListedCompany("NWL"));
        Companies.getListedCompanies().add(new ListedCompany("NEM"));
        Companies.getListedCompanies().add(new ListedCompany("NWSA"));
        Companies.getListedCompanies().add(new ListedCompany("NWS"));
        Companies.getListedCompanies().add(new ListedCompany("NEE"));
        Companies.getListedCompanies().add(new ListedCompany("NLSN"));
        Companies.getListedCompanies().add(new ListedCompany("NKE"));
        Companies.getListedCompanies().add(new ListedCompany("NI"));
        Companies.getListedCompanies().add(new ListedCompany("NSC"));
        Companies.getListedCompanies().add(new ListedCompany("NTRS"));
        Companies.getListedCompanies().add(new ListedCompany("NOC"));
        Companies.getListedCompanies().add(new ListedCompany("NLOK"));
        Companies.getListedCompanies().add(new ListedCompany("NCLH"));
        Companies.getListedCompanies().add(new ListedCompany("NOV"));
        Companies.getListedCompanies().add(new ListedCompany("NRG"));
        Companies.getListedCompanies().add(new ListedCompany("NUE"));
        Companies.getListedCompanies().add(new ListedCompany("NVDA"));
        Companies.getListedCompanies().add(new ListedCompany("NVR"));
        Companies.getListedCompanies().add(new ListedCompany("NXPI"));
        Companies.getListedCompanies().add(new ListedCompany("ORLY"));
        Companies.getListedCompanies().add(new ListedCompany("OXY"));
        Companies.getListedCompanies().add(new ListedCompany("ODFL"));
        Companies.getListedCompanies().add(new ListedCompany("OMC"));
        Companies.getListedCompanies().add(new ListedCompany("OKE"));
        Companies.getListedCompanies().add(new ListedCompany("ORCL"));
        Companies.getListedCompanies().add(new ListedCompany("OGN"));
        Companies.getListedCompanies().add(new ListedCompany("OTIS"));
        Companies.getListedCompanies().add(new ListedCompany("PCAR"));
        Companies.getListedCompanies().add(new ListedCompany("PKG"));
        Companies.getListedCompanies().add(new ListedCompany("PH"));
        Companies.getListedCompanies().add(new ListedCompany("PAYX"));
        Companies.getListedCompanies().add(new ListedCompany("PAYC"));
        Companies.getListedCompanies().add(new ListedCompany("PYPL"));
        Companies.getListedCompanies().add(new ListedCompany("PENN"));
        Companies.getListedCompanies().add(new ListedCompany("PNR"));
        Companies.getListedCompanies().add(new ListedCompany("PBCT"));
        Companies.getListedCompanies().add(new ListedCompany("PEP"));
        Companies.getListedCompanies().add(new ListedCompany("PKI"));
        Companies.getListedCompanies().add(new ListedCompany("PRGO"));
        Companies.getListedCompanies().add(new ListedCompany("PFE"));
        Companies.getListedCompanies().add(new ListedCompany("PM"));
        Companies.getListedCompanies().add(new ListedCompany("PSX"));
        Companies.getListedCompanies().add(new ListedCompany("PNW"));
        Companies.getListedCompanies().add(new ListedCompany("PXD"));
        Companies.getListedCompanies().add(new ListedCompany("PNC"));
        Companies.getListedCompanies().add(new ListedCompany("POOL"));
        Companies.getListedCompanies().add(new ListedCompany("PPG"));
        Companies.getListedCompanies().add(new ListedCompany("PPL"));
        Companies.getListedCompanies().add(new ListedCompany("PFG"));
        Companies.getListedCompanies().add(new ListedCompany("PG"));
        Companies.getListedCompanies().add(new ListedCompany("PGR"));
        Companies.getListedCompanies().add(new ListedCompany("PLD"));
        Companies.getListedCompanies().add(new ListedCompany("PRU"));
        Companies.getListedCompanies().add(new ListedCompany("PTC"));
        Companies.getListedCompanies().add(new ListedCompany("PEG"));
        Companies.getListedCompanies().add(new ListedCompany("PSA"));
        Companies.getListedCompanies().add(new ListedCompany("PHM"));
        Companies.getListedCompanies().add(new ListedCompany("PVH"));
        Companies.getListedCompanies().add(new ListedCompany("QRVO"));
        Companies.getListedCompanies().add(new ListedCompany("PWR"));
        Companies.getListedCompanies().add(new ListedCompany("QCOM"));
        Companies.getListedCompanies().add(new ListedCompany("DGX"));
        Companies.getListedCompanies().add(new ListedCompany("RL"));
        Companies.getListedCompanies().add(new ListedCompany("RJF"));
        Companies.getListedCompanies().add(new ListedCompany("RTX"));
        Companies.getListedCompanies().add(new ListedCompany("O"));
        Companies.getListedCompanies().add(new ListedCompany("REG"));
        Companies.getListedCompanies().add(new ListedCompany("REGN"));
        Companies.getListedCompanies().add(new ListedCompany("RF"));
        Companies.getListedCompanies().add(new ListedCompany("RSG"));
        Companies.getListedCompanies().add(new ListedCompany("RMD"));
        Companies.getListedCompanies().add(new ListedCompany("RHI"));
        Companies.getListedCompanies().add(new ListedCompany("ROK"));
        Companies.getListedCompanies().add(new ListedCompany("ROL"));
        Companies.getListedCompanies().add(new ListedCompany("ROP"));
        Companies.getListedCompanies().add(new ListedCompany("ROST"));
        Companies.getListedCompanies().add(new ListedCompany("RCL"));
        Companies.getListedCompanies().add(new ListedCompany("SPGI"));
        Companies.getListedCompanies().add(new ListedCompany("CRM"));
        Companies.getListedCompanies().add(new ListedCompany("SBAC"));
        Companies.getListedCompanies().add(new ListedCompany("SLB"));
        Companies.getListedCompanies().add(new ListedCompany("STX"));
        Companies.getListedCompanies().add(new ListedCompany("SEE"));
        Companies.getListedCompanies().add(new ListedCompany("SRE"));
        Companies.getListedCompanies().add(new ListedCompany("NOW"));
        Companies.getListedCompanies().add(new ListedCompany("SHW"));
        Companies.getListedCompanies().add(new ListedCompany("SPG"));
        Companies.getListedCompanies().add(new ListedCompany("SWKS"));
        Companies.getListedCompanies().add(new ListedCompany("SNA"));
        Companies.getListedCompanies().add(new ListedCompany("SO"));
        Companies.getListedCompanies().add(new ListedCompany("LUV"));
        Companies.getListedCompanies().add(new ListedCompany("SWK"));
        Companies.getListedCompanies().add(new ListedCompany("SBUX"));
        Companies.getListedCompanies().add(new ListedCompany("STT"));
        Companies.getListedCompanies().add(new ListedCompany("STE"));
        Companies.getListedCompanies().add(new ListedCompany("SYK"));
        Companies.getListedCompanies().add(new ListedCompany("SIVB"));
        Companies.getListedCompanies().add(new ListedCompany("SYF"));
        Companies.getListedCompanies().add(new ListedCompany("SNPS"));
        Companies.getListedCompanies().add(new ListedCompany("SYY"));
        Companies.getListedCompanies().add(new ListedCompany("TMUS"));
        Companies.getListedCompanies().add(new ListedCompany("TROW"));
        Companies.getListedCompanies().add(new ListedCompany("TTWO"));
        Companies.getListedCompanies().add(new ListedCompany("TPR"));
        Companies.getListedCompanies().add(new ListedCompany("TGT"));
        Companies.getListedCompanies().add(new ListedCompany("TEL"));
        Companies.getListedCompanies().add(new ListedCompany("TDY"));
        Companies.getListedCompanies().add(new ListedCompany("TFX"));
        Companies.getListedCompanies().add(new ListedCompany("TER"));
        Companies.getListedCompanies().add(new ListedCompany("TSLA"));
        Companies.getListedCompanies().add(new ListedCompany("TXN"));
        Companies.getListedCompanies().add(new ListedCompany("TXT"));
        Companies.getListedCompanies().add(new ListedCompany("TMO"));
        Companies.getListedCompanies().add(new ListedCompany("TJX"));
        Companies.getListedCompanies().add(new ListedCompany("TSCO"));
        Companies.getListedCompanies().add(new ListedCompany("TT"));
        Companies.getListedCompanies().add(new ListedCompany("TDG"));
        Companies.getListedCompanies().add(new ListedCompany("TRV"));
        Companies.getListedCompanies().add(new ListedCompany("TRMB"));
        Companies.getListedCompanies().add(new ListedCompany("TFC"));
        Companies.getListedCompanies().add(new ListedCompany("TWTR"));
        Companies.getListedCompanies().add(new ListedCompany("TYL"));
        Companies.getListedCompanies().add(new ListedCompany("TSN"));
        Companies.getListedCompanies().add(new ListedCompany("UDR"));
        Companies.getListedCompanies().add(new ListedCompany("ULTA"));
        Companies.getListedCompanies().add(new ListedCompany("USB"));
        Companies.getListedCompanies().add(new ListedCompany("UAA"));
        Companies.getListedCompanies().add(new ListedCompany("UA"));
        Companies.getListedCompanies().add(new ListedCompany("UNP"));
        Companies.getListedCompanies().add(new ListedCompany("UAL"));
        Companies.getListedCompanies().add(new ListedCompany("UNH"));
        Companies.getListedCompanies().add(new ListedCompany("UPS"));
        Companies.getListedCompanies().add(new ListedCompany("URI"));
        Companies.getListedCompanies().add(new ListedCompany("UHS"));
        Companies.getListedCompanies().add(new ListedCompany("UNM"));
        Companies.getListedCompanies().add(new ListedCompany("VLO"));
        Companies.getListedCompanies().add(new ListedCompany("VTR"));
        Companies.getListedCompanies().add(new ListedCompany("VRSN"));
        Companies.getListedCompanies().add(new ListedCompany("VRSK"));
        Companies.getListedCompanies().add(new ListedCompany("VZ"));
        Companies.getListedCompanies().add(new ListedCompany("VRTX"));
        Companies.getListedCompanies().add(new ListedCompany("VFC"));
        Companies.getListedCompanies().add(new ListedCompany("VIAC"));
        Companies.getListedCompanies().add(new ListedCompany("VTRS"));
        Companies.getListedCompanies().add(new ListedCompany("V"));
        Companies.getListedCompanies().add(new ListedCompany("VNO"));
        Companies.getListedCompanies().add(new ListedCompany("VMC"));
        Companies.getListedCompanies().add(new ListedCompany("WRB"));
        Companies.getListedCompanies().add(new ListedCompany("WAB"));
        Companies.getListedCompanies().add(new ListedCompany("WMT"));
        Companies.getListedCompanies().add(new ListedCompany("WBA"));
        Companies.getListedCompanies().add(new ListedCompany("DIS"));
        Companies.getListedCompanies().add(new ListedCompany("WM"));
        Companies.getListedCompanies().add(new ListedCompany("WAT"));
        Companies.getListedCompanies().add(new ListedCompany("WEC"));
        Companies.getListedCompanies().add(new ListedCompany("WFC"));
        Companies.getListedCompanies().add(new ListedCompany("WELL"));
        Companies.getListedCompanies().add(new ListedCompany("WST"));
        Companies.getListedCompanies().add(new ListedCompany("WDC"));
        Companies.getListedCompanies().add(new ListedCompany("WU"));
        Companies.getListedCompanies().add(new ListedCompany("WRK"));
        Companies.getListedCompanies().add(new ListedCompany("WY"));
        Companies.getListedCompanies().add(new ListedCompany("WHR"));
        Companies.getListedCompanies().add(new ListedCompany("WMB"));
        Companies.getListedCompanies().add(new ListedCompany("WLTW"));
        Companies.getListedCompanies().add(new ListedCompany("WYNN"));
        Companies.getListedCompanies().add(new ListedCompany("XEL"));
        Companies.getListedCompanies().add(new ListedCompany("XLNX"));
        Companies.getListedCompanies().add(new ListedCompany("XYL"));
        Companies.getListedCompanies().add(new ListedCompany("YUM"));
        Companies.getListedCompanies().add(new ListedCompany("ZBRA"));
        Companies.getListedCompanies().add(new ListedCompany("ZBH"));
        Companies.getListedCompanies().add(new ListedCompany("ZION"));
        Companies.getListedCompanies().add(new ListedCompany("ZTS"));

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            Companies.getListedCompanies().sort(Comparator.comparing(ListedCompany::getCompanySymbol));
        }

        dataDB(this);
    }

    public void dataDB(Context context) {
        String url = "http://192.168.100.18/vesting_webservice/read_user_by_id.php";

        RequestQueue mQueue = Volley.newRequestQueue(context);

        StringRequest request = new StringRequest(Request.Method.POST, url, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                System.out.println(response);

                try {
                    JSONObject jsonObject = new JSONObject(response);
                    JSONObject objUser = jsonObject.getJSONObject("user");

                    UserArray.currentUser.setBalance(objUser.getDouble("balance"));
                } catch (JSONException err) {
                    err.printStackTrace();
                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                error.printStackTrace();
            }
        }) {
            @Override
            public String getBodyContentType() {
                return "application/x-www-form-urlencoded; charset=UTF-8";
            }

            @Override
            protected Map<String, String> getParams() {
                Map<String, String> params = new HashMap<String, String>();

                params.put("user_id", String.valueOf(UserArray.currentUser.getId()));

                return params;
            }
        };

        mQueue.add(request);
    }

}